#define II_ANSIBLE_ADDR       0xA0
#define II_GET                128
#define II_ANSIBLE_TR         1
#define II_ANSIBLE_TR_TOG     2
#define II_ANSIBLE_TR_PULSE   3
#define II_ANSIBLE_TR_TIME    4
#define II_ANSIBLE_TR_POL     5
#define II_ANSIBLE_CV         6
#define II_ANSIBLE_CV_SLEW    7
#define II_ANSIBLE_CV_OFF     8
#define II_ANSIBLE_CV_SET     9
#define II_ANSIBLE_INPUT      10

#define JF_ADDR 	0xF0
#define JF_TR 		1
#define JF_RMODE 	2
#define JF_RUN 		3
#define JF_SHIFT 	4
#define JF_VTR 		5
#define JF_MODE 	6
#define JF_TICK 	7
#define JF_VOX 		8
#define JF_NOTE 	9
#define JF_GOD 		10
#define JF_TUNE		11
#define JF_QT		12

#define WW 				0x10
#define WW_PRESET 		0x11
#define WW_POS			0x12
#define WW_SYNC			0x13
#define WW_START		0x14
#define WW_END			0x15
#define WW_PMODE		0x16
#define WW_PATTERN		0x17
#define WW_QPATTERN		0x18
#define WW_MUTE1		0x19
#define WW_MUTE2		0x1A
#define WW_MUTE3		0x1B
#define WW_MUTE4		0x1C
#define WW_MUTEA		0x1D
#define WW_MUTEB		0x1E

#define MP 				0x30
#define MP_PRESET		0x31
#define MP_RESET		0x32
#define MP_SYNC			0x33
#define MP_MUTE			0x34
#define MP_UNMUTE		0x35
#define MP_FREEZE		0x36
#define MP_UNFREEZE		0x37
#define MP_STOP			0x38

#define ES 				0x50
#define ES_PRESET		0x51
#define ES_MODE			0x52
#define ES_CLOCK		0x53
#define ES_RESET		0x54
#define ES_PATTERN		0x55
#define ES_TRANS		0x56
#define ES_STOP			0x57
#define ES_TRIPLE		0x58
#define ES_MAGIC		0x59

#define ORCA			0x40
#define ORCA_TRACK		0x40
#define ORCA_CLOCK		0x41
#define ORCA_DIVISOR	0x42
#define ORCA_PHASE		0x43
#define ORCA_RESET		0x44
#define ORCA_WEIGHT		0x45
#define ORCA_MUTE		0x46
#define ORCA_SCALE		0x47
#define ORCA_BANK		0x48
#define ORCA_PRESET		0x49
#define ORCA_RELOAD		0x4A
#define ORCA_ROTATES	0x4B
#define ORCA_ROTATEW	0x4C
#define ORCA_GRESET		0x4D
#define ORCA_CVA		0x4E
#define ORCA_CVB		0x4F
